version: '3.7'

networks:
  default:
    name: some-store-network

volumes:
  database:

services:
  mongo:
    image: mongo:4.4.4-bionic
    container_name: "aspnet-store-mongo"
    hostname: aspnet-store-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
