version: '3.7'

networks:
  default:
    name: some-store-network
    
services:
  aspnet_store_internal:
    build:
      context: ../../
      dockerfile: ./Source/Store.WebApi.Internal/Dockerfile
    container_name: aspnet_store_internal
    hostname: aspnet_store_internal
    restart: "always"
    ports:
      - "1337:80"
    environment:
      "DbConfig__ConnectionString": mongodb://aspnet-store-mongo:27017
      "CacheOptions__Server": aspnet_store_redis:6379


